=== gigs2go/TableService/tableservice/src/main/resources/schemas/data.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">

    <xs:element name="data" type="Data"/>

    <xs:complexType name="Data">
        <xs:sequence>
            <xs:element name="schemaName" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="rows">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="row" type="Row"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ColumnValue">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Row">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="columnvalue" type="ColumnValue"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== gigs2go/TableService/tableservice/src/test/resources/TestData0.xml
<?xml version="1.0" encoding="utf-8"?>
<data  xmlns:o="http://www.ensignos.com/data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ensignos.com/data ../../main/webapp/schemas/data.xsd ">
	<schemaName>SchemaName</schemaName>
	<name>FileName</name>
		<rows>
			<row>
				<columnvalue>
					<name>String</name>
					<value>String value</value>
				</columnvalue>
				<columnvalue>
					<name>Decimal</name>
					<value>1.23</value>
				</columnvalue>
			</row>
		</rows>
</data>
