=== gigs2go/TableService/tableservice/src/main/resources/schemas/schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">

    <xs:element name="schema" type="Schema"/>

    <xs:complexType name="Schema">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="version" type="xs:decimal" minOccurs="0" maxOccurs="1"/>
            <xs:element name="creationDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
            <xs:element name="columns">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="column" type="Column"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Column">
        <xs:sequence>
            <xs:element name="dataType" type="ColumnDataType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="type" type="ColumnType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="indexed" type="xs:boolean" minOccurs="0" maxOccurs="1" default="false"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="ColumnDataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="INTEGER"/>
            <xs:enumeration value="DECIMAL"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="DATE"/>
            <xs:enumeration value="YEAR"/>
            <xs:enumeration value="DATETIME"/>
            <xs:enumeration value="EMAIL"/>
            <xs:enumeration value="URL"/>
            <xs:enumeration value="CURRENCY"/>
            <xs:enumeration value="PERCENT"/>
            <xs:enumeration value="TIMESTAMP"/>
            <xs:enumeration value="BOOLEAN"/>
            <xs:enumeration value="VERSION"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ColumnType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DIMENSION"/>
            <xs:enumeration value="MEASURE"/>
            <xs:enumeration value="TEXT"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== gigs2go/TableService/tableservice/src/test/resources/TestSchema1.xml
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ensignos.com/schema ../../main/webapp/schemas/schema.xsd">
    <name>SchemaOne</name>
    <version>0.1</version>
    <creationDate>2013-06-15</creationDate>
    <columns>
        <column>
            <dataType>STRING</dataType>
            <type>DIMENSION</type>
            <name>Code</name>
        </column>
        <column>
            <dataType>STRING</dataType>
            <type>DIMENSION</type>
            <name>Name</name>
        </column>
        <column>
            <dataType>STRING</dataType>
            <type>DIMENSION</type>
            <name>Continent</name>
        </column>
        <column>
            <dataType>STRING</dataType>
            <type>DIMENSION</type>
            <name>Region</name>
        </column>
        <column>
            <dataType>DOUBLE</dataType>
            <type>MEASURE</type>
            <name>SurfaceArea</name>
        </column>
        <column>
            <dataType>YEAR</dataType>
            <type>DIMENSION</type>
            <name>IndepYear</name>
        </column>
        <column>
            <dataType>INTEGER</dataType>
            <type>MEASURE</type>
            <name>Population</name>
        </column>
        <column>
            <dataType>DOUBLE</dataType>
            <type>MEASURE</type>
            <name>LifeExpectancy</name>
        </column>
        <column>
            <dataType>DOUBLE</dataType>
            <type>MEASURE</type>
            <name>GNP</name>
        </column>
        <column>
            <dataType>DOUBLE</dataType>
            <type>MEASURE</type>
            <name>GNPOld</name>
        </column>
        <column>
            <dataType>STRING</dataType>
            <type>TEXT</type>
            <name>LocalName</name>
        </column>
        <column>
            <dataType>STRING</dataType>
            <type>DIMENSION</type>
            <name>GovernmentForm</name>
        </column>
        <column>
            <dataType>STRING</dataType>
            <type>TEXT</type>
            <name>HeadOfState</name>
        </column>
        <column>
            <dataType>INTEGER</dataType>
            <type>TEXT</type>
            <name>Capital</name>
        </column>
        <column>
            <dataType>STRING</dataType>
            <type>TEXT</type>
            <name>Code2</name>
        </column>
    </columns>
</schema>

=== gigs2go/TableService/tableservice/src/test/resources/TestSchemaError.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ensignos.com/schema ../../main/webapp/schemas/schema.xsd">
		<name>SchemaName</name>
		<version>99.0.9</version>
		<creationDate>2013-06-15</creationDate>
		<columns>
			<column>
				<dataType>STRING</dataType>
				<type>DIMENSION</type>
				<name>String</name>
			</column>
		</columns>
</schema>

=== gigs2go/TableService/tableservice/src/test/resources/TestSchema0.xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ensignos.com/schema ../../main/webapp/schemas/schema.xsd">
		<name>SchemaName</name>
		<version>0.1</version>
		<creationDate>2013-06-15</creationDate>
		<columns>
			<column>
				<dataType>STRING</dataType>
				<type>DIMENSION</type>
				<name>String</name>
			</column>
			<column>
				<dataType>EMAIL</dataType>
				<type>TEXT</type>
				<name>Email</name>
				<indexed>true</indexed>
			</column>
			<column>
				<dataType>URL</dataType>
				<type>TEXT</type>
				<name>Url</name>
			</column>
			<column>
				<dataType>INTEGER</dataType>
				<type>MEASURE</type>
				<name>Integer</name>
			</column>
			<column>
				<dataType>CURRENCY</dataType>
				<type>MEASURE</type>
				<name>Currency</name>
			</column>
			<column>
				<dataType>PERCENT</dataType>
				<type>MEASURE</type>
				<name>Percent</name>
			</column>
			<column>
				<dataType>DATE</dataType>
				<type>DIMENSION</type>
				<name>Date</name>
			</column>
			<column>
				<dataType>DATETIME</dataType>
				<type>DIMENSION</type>
				<name>DateTime</name>
			</column>
			<column>
				<dataType>TIMESTAMP</dataType>
				<type>DIMENSION</type>
				<name>TimeStamp</name>
			</column>
			<column>
				<dataType>BOOLEAN</dataType>
				<type>DIMENSION</type>
				<name>Boolean</name>
			</column>
			<column>
				<dataType>VERSION</dataType>
				<type>DIMENSION</type>
				<name>Version</name>
			</column>
			<column>
				<dataType>DECIMAL</dataType>
				<type>MEASURE</type>
				<name>Decimal</name>
			</column>
			<column>
				<dataType>DOUBLE</dataType>
				<type>MEASURE</type>
				<name>Double</name>
			</column>
		</columns>
</schema>
